"use client";

import React from "react";

export function InvoiceWatermark() {
  return (
    <div className="mt-12 flex items-center justify-center border-t border-[color:var(--border-subtle)] pt-6 text-center opacity-40 grayscale transition-all hover:opacity-80 hover:grayscale-0 print:hidden print:m-0 print:p-0 print:h-0 print:overflow-hidden">
      <p className="text-[10px] font-medium tracking-wider text-[color:var(--text-muted)]">
        GENERATED BY{" "}
        <span className="font-bold text-[color:var(--text-primary)]">
          LANCEINVOICE
        </span>
      </p>
    </div>
  );
}
